import { ref } from 'vue'
import { LibraryService } from '@/services/libraryService'

export const useLibrary = () => {
    const token = ref<string|null>(
        import.meta.client ? localStorage.getItem('access_token') : null
    )
    const error = ref<string>('');
    const isLoading = ref<boolean>(false);
    const rulebooks = ref<any[]>([]);
    const currentRulebook = ref<any>(null);

    const getAllRulebooks = async () => {
        error.value = '';
        isLoading.value = true;

        try {
            const response = await LibraryService.fetchAllRulebooks();
            
            // The 'content' array is generated by Spring Boot's Page object
            rulebooks.value = response.content;
            console.log('fetched', response.content);
        } catch(err: any) {
            error.value = err.data?.message || 'No rulebooks found'
            error.value = err.data?.message || 'No rulebooks found'
            rulebooks.value = []
        } finally {
            isLoading.value = false;
        }
    }

    const getRulebookById = async (id: string) => {
        error.value = '';
        isLoading.value = true;
        currentRulebook.value = null;

        try{
            const rawData = await LibraryService.fetchRulebookById(id);
            currentRulebook.value = rawData;
        }catch(err: any){
            console.error(`Failed to fetch rulebook ${id}:`, err);
            error.value = err.data?.message || 'Failed to load rulebook details';
        }finally{
            isLoading.value = false;
        }
    }

    const rulebookText = ref<any>(null)

    const getRulebookText = async (id: string) => {
        try {
            const response = await LibraryService.fetchRulebookText(id)
            rulebookText.value = response;
        } catch (err: any) {
            console.error(`Failed to fetch rulebook text ${id}:`, err)
            rulebookText.value = null
        }
    }


    return {
        token,
        error,
        isLoading,
        rulebooks,
        currentRulebook,
        rulebookText,
        getAllRulebooks,
        getRulebookById,
        getRulebookText
    }
}