import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { LibraryService } from '~/services/libraryService'

export const useLibrary = () => {
    const router = useRouter();

    const token = ref<string|null>(
        import.meta.client ? localStorage.getItem('access_token') : null
    )
    const error = ref<string>('');
    const loading = ref<boolean>(false);

    const rulebooks = ref<any[]>([]);

    const getAllRulebooks = async () => {
        error.value = '';
        loading.value = true;

        try {
            const response = await LibraryService.getAllRulebooks();
            
            // The 'content' array is generated by Spring Boot's Page object
            rulebooks.value = response.data.content; 
            
        } catch(err: any) {
            error.value = err.response?.data?.message || 'No rulebooks found'
            rulebooks.value = []
        } finally {
            loading.value = false;
        }
    }

    return {
        token,
        error,
        loading,
        rulebooks,
        getAllRulebooks
    }
}