spring.application.name=scrapers

#db
spring.mongodb.database=boardwise

rulebook.pdf.api.url =${RULEBOOK_PDF_API}

ai.gateway.internal-secret=${INTERNAL_SECRET}
python.api.base.url=${PYTHON_API_BASE_URL}

spring.mongodb.uri=${DEV_DB_URL}


scrape.cache.refresh.interval.ms=3600000

server.port=8082