from enum import StrEnum


class VlmStatus(StrEnum):
    OK = "OK"
    EMPTY = "EMPTY"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    API_ERROR = "API_ERROR"
    RENDER_ERROR = "RENDER_ERROR"
    RECITATION = "RECITATION"
    SAFETY = "SAFETY"
    MAX_TOKENS = "MAX_TOKENS"
    DAILY_CAP_EXHAUSTED = "DAILY_CAP_EXHAUSTED"
    RETRIES_EXHAUSTED = "RETRIES_EXHAUSTED"
