SEED_MECHANICS: list[dict] = [
    {
        "mechanicId": 2001,
        "name": "Action Points",
        "category": "Action",
        "typical_game_category": "Miniatures",
        "description": "Players receive a specific allowance of points at the beginning of their turn to spend on various available activities. Each activity costs a predefined number of these points, allowing for flexible turn structures.",
    },
    {
        "mechanicId": 2002,
        "name": "Income",
        "category": "Resource",
        "typical_game_category": "Economic",
        "description": "Participants receive a steady distribution of resources or currency at specific, regular intervals during play. This structured payout supports ongoing economic development and long-term planning.",
    },
    {
        "mechanicId": 2003,
        "name": "Investment",
        "category": "Resource",
        "typical_game_category": "Economic",
        "description": "Players expend current resources or currency to secure a larger return of assets at a later stage of play. This requires balancing immediate needs against future economic advantages.",
    },
    {
        "mechanicId": 2004,
        "name": "Set Collection",
        "category": "Scoring",
        "typical_game_category": "Card Game",
        "description": "Participants gather specific groupings of related items or symbols to earn rewards or victory points. The value of these groupings often increases non-linearly as the collection grows closer to completion.",
    },
    {
        "mechanicId": 2007,
        "name": "Pick-up and Deliver",
        "category": "Movement",
        "typical_game_category": "Transportation",
        "description": "Players navigate a playing area to collect items at designated starting locations and transport them to specific destinations. Successfully completing these transport routes yields currency, points, or other advantages.",
    },
    {
        "mechanicId": 2008,
        "name": "Trading",
        "category": "Social",
        "typical_game_category": "Negotiation",
        "description": "Participants exchange resources, currency, or components with one another to improve their individual positions. These transactions rely on mutual agreement and negotiation to determine the value of the exchanged goods.",
    },
    {
        "mechanicId": 2009,
        "name": "Trick-taking",
        "category": "Card",
        "typical_game_category": "Card Game",
        "description": "Participants sequentially reveal components, usually cards, with the highest-valued element capturing the entire grouping played during that round. Success depends on strategically managing a limited hand of components over multiple consecutive rounds.",
    },
    {
        "mechanicId": 2010,
        "name": "Stock Holding",
        "category": "Resource",
        "typical_game_category": "Economic",
        "description": "Individuals acquire shares in various entities, tying their personal success to the fluctuating value and performance of those entities. The entities operate independently, often influenced by the collective actions of all shareholders.",
    },
    {
        "mechanicId": 2011,
        "name": "Modular Board",
        "category": "Structural",
        "typical_game_category": "Miniatures",
        "description": "The playing area is constructed from multiple independent pieces that can be arranged in various configurations. This ensures a distinct geographic layout and spatial relationship between elements for every session.",
    },
    {
        "mechanicId": 2012,
        "name": "Auction/Bidding",
        "category": "Auction",
        "typical_game_category": "Economic",
        "description": "Participants compete for resources or advantages by offering incrementally higher amounts of currency or assets. The highest offer secures the desired item, forcing individuals to constantly evaluate the worth of available assets.",
    },
    {
        "mechanicId": 2013,
        "name": "Commodity Speculation",
        "category": "Resource",
        "typical_game_category": "Economic",
        "description": "Players acquire goods with the expectation that the monetary value of those goods will fluctuate throughout the session. Success relies on accurately predicting market changes to buy goods at a low cost and sell them at a premium.",
    },
    {
        "mechanicId": 2014,
        "name": "Betting and Bluffing",
        "category": "Social",
        "typical_game_category": "Card Game",
        "description": "Participants risk currency or resources on uncertain outcomes while intentionally misrepresenting their own concealed information or intentions. This creates a psychological environment where deducing the truth behind opponents' claims is as critical as managing probabilities.",
    },
    {
        "mechanicId": 2015,
        "name": "Variable Player Powers",
        "category": "Structural",
        "typical_game_category": "Fantasy",
        "description": "Each participant receives unique abilities, rule exceptions, or starting conditions that differentiate them from their opponents. This asymmetry encourages distinct strategic approaches and personal objectives throughout the session.",
    },
    {
        "mechanicId": 2016,
        "name": "Closed Economy Auction",
        "category": "Auction",
        "typical_game_category": "Ancient",
        "description": "Participants bid for items using a finite pool of currency that circulates entirely among the players rather than returning to a central bank. Currency spent to win an item is immediately distributed to the other participants, maintaining a strict economic equilibrium.",
    },
    {
        "mechanicId": 2017,
        "name": "Voting",
        "category": "Social",
        "typical_game_category": "Party Game",
        "description": "Participants collectively influence the outcome of events, rule changes, or player eliminations by casting formal choices. The results depend on building majorities or reaching consensus, often requiring negotiation and alliance-building.",
    },
    {
        "mechanicId": 2018,
        "name": "Tile Placement",
        "category": "Structural",
        "typical_game_category": "Abstract Strategy",
        "description": "Players position flat, geometrically shaped components onto a central playing area to create a growing landscape or structural layout. Points or resources are typically awarded based on how newly positioned components align with previously established features.",
    },
    {
        "mechanicId": 2019,
        "name": "Auction: Once Around",
        "category": "Auction",
        "typical_game_category": "Economic",
        "description": "Participants compete for an item through a strictly structured process where each person is granted exactly one opportunity to declare an offer or pass. The process concludes after a single rotation, preventing continuous escalation of offers.",
    },
    {
        "mechanicId": 2020,
        "name": "Simultaneous Action Selection",
        "category": "Action",
        "typical_game_category": "Card Game",
        "description": "All participants secretly choose their intended moves at the same time and then reveal their decisions concurrently. This creates psychological tension as individuals must anticipate opponents' choices without the benefit of observing them first.",
    },
    {
        "mechanicId": 2023,
        "name": "Cooperative Game",
        "category": "Structural",
        "typical_game_category": "Fantasy",
        "description": "Participants coordinate their efforts to overcome challenges dictated by the system itself rather than competing against one another. Success or failure is shared equally among all individuals based on their collective ability to achieve a common objective.",
    },
    {
        "mechanicId": 2024,
        "name": "Race",
        "category": "Movement",
        "typical_game_category": "Racing",
        "description": "Participants compete to be the first to reach a specific spatial destination or fulfill a designated set of requirements. The session ends immediately upon a participant achieving the milestone, rendering accumulated points or secondary resources irrelevant.",
    },
    {
        "mechanicId": 2025,
        "name": "Random Production",
        "category": "Resource",
        "typical_game_category": "Economic",
        "description": "The generation of resources or assets is determined by unpredictable events, such as rolling dice or drawing cards. Participants must position themselves strategically to benefit from these variable distributions while mitigating the risks of unfavorable outcomes.",
    },
    {
        "mechanicId": 2026,
        "name": "Hexagon Grid",
        "category": "Structural",
        "typical_game_category": "Wargame",
        "description": "The playing surface is divided into a network of six-sided spaces, allowing movement and adjacencies in six different directions. This geometric arrangement provides equidistant movement paths and complex spatial relationships compared to traditional square grids.",
    },
    {
        "mechanicId": 2027,
        "name": "Storytelling",
        "category": "Social",
        "typical_game_category": "Card Game",
        "description": "Participants verbally construct a collaborative narrative or expand upon thematic prompts provided by the system. Success relies heavily on creativity, improvisation, and the ability to weave disparate elements into a cohesive narrative structure.",
    },
    {
        "mechanicId": 2028,
        "name": "Role Playing",
        "category": "Social",
        "typical_game_category": "Adventure",
        "description": "Participants adopt specific personas and make decisions based on the motivations and knowledge of those characters. Interactions rely on thematic immersion and often involve verbal communication to advance the overarching narrative.",
    },
    {
        "mechanicId": 2029,
        "name": "Enclosure",
        "category": "Structural",
        "typical_game_category": "Abstract Strategy",
        "description": "Participants place components to surround or capture specific areas on the playing surface. Successfully isolating a region typically grants ownership, points, or resources to the individual who completes the continuous boundary.",
    },
    {
        "mechanicId": 2032,
        "name": "Player Elimination",
        "category": "Structural",
        "typical_game_category": "Card Game",
        "description": "Participants are permanently removed from the session when they meet specific failure conditions. The remaining individuals continue playing until a single victor remains or another endgame parameter is triggered.",
    },
    {
        "mechanicId": 2034,
        "name": "Variable Phase Order",
        "category": "Turn Order",
        "typical_game_category": "Fantasy",
        "description": "The sequence of distinct structural steps in a round is not fixed, but rather determined by participant choices. Selected steps are executed in a specific hierarchy by everyone, while unselected steps are skipped entirely for that round.",
    },
    {
        "mechanicId": 2035,
        "name": "Roll / Spin and Move",
        "category": "Movement",
        "typical_game_category": "Children's Game",
        "description": "Participants advance their pieces along a track based on the unpredictable outcome of a physical randomizer. The exact destination is determined solely by this generated value, leaving minimal spatial decision-making to the individual.",
    },
    {
        "mechanicId": 2040,
        "name": "Hand Management",
        "category": "Card",
        "typical_game_category": "Card Game",
        "description": "Participants must optimize the use of a limited set of concealed components held in their possession. Success requires balancing the immediate benefits of playing specific elements against the need to retain others for future opportunities.",
    },
    {
        "mechanicId": 2041,
        "name": "Card Drafting",
        "category": "Card",
        "typical_game_category": "Card Game",
        "description": "Participants select individual components from a shared or rotating pool to build their personal collections. This requires evaluating the relative worth of available options while anticipating the needs and potential selections of opponents.",
    },
    {
        "mechanicId": 2043,
        "name": "Deduction",
        "category": "Other",
        "typical_game_category": "Bluffing",
        "description": "Participants use logic and partial information to uncover hidden identities, locations, or solutions. Success depends on systematically eliminating incorrect possibilities based on clues provided by the system or opponent behaviors.",
    },
    {
        "mechanicId": 2046,
        "name": "Area Movement",
        "category": "Movement",
        "typical_game_category": "Wargame",
        "description": "The playing surface is divided into distinct, irregularly shaped regions of varying sizes. Pieces transition between these adjacent regions rather than moving along a structured grid or measured physical distance.",
    },
    {
        "mechanicId": 2047,
        "name": "Memory",
        "category": "Other",
        "typical_game_category": "Card Game",
        "description": "Participants must recall hidden or previously revealed information to make optimal decisions. Success relies on accurate mental tracking of component locations, opponent resources, or past actions.",
    },
    {
        "mechanicId": 2048,
        "name": "Pattern Building",
        "category": "Structural",
        "typical_game_category": "Abstract Strategy",
        "description": "Participants arrange physical components into specific geometric configurations or sequences. Achieving the required spatial arrangements yields rewards, abilities, or progression toward victory conditions.",
    },
    {
        "mechanicId": 2049,
        "name": "Pattern Recognition",
        "category": "Other",
        "typical_game_category": "Card Game",
        "description": "Participants must quickly identify matching visual elements, sequences, or spatial relationships among displayed components. Success typically rewards the fastest individual to correctly spot and declare the required configuration.",
    },
    {
        "mechanicId": 2057,
        "name": "Chit-Pull System",
        "category": "Turn Order",
        "typical_game_category": "Wargame",
        "description": "The sequence of actions or active factions is determined by blindly drawing tokens from a centralized container. This introduces unpredictability into the timeline, forcing individuals to adapt their strategies to a constantly changing activation order.",
    },
    {
        "mechanicId": 2070,
        "name": "Simulation",
        "category": "Other",
        "typical_game_category": "Wargame",
        "description": "The system attempts to realistically model a specific historical, economic, or physical process. Rules and interactions are designed to mirror real-world constraints, probabilities, and outcomes as accurately as possible.",
    },
    {
        "mechanicId": 2072,
        "name": "Dice Rolling",
        "category": "Dice",
        "typical_game_category": "Wargame",
        "description": "Participants rely on physical, multi-sided randomizers to determine the outcomes of specific actions or events. The generated values introduce variability and risk management into strategic decision-making.",
    },
    {
        "mechanicId": 2073,
        "name": "Acting",
        "category": "Social",
        "typical_game_category": "Party Game",
        "description": "Participants perform physical gestures, mime, or vocalizations to convey concepts to others without using explicit spoken descriptions. Success relies on expressive communication and the interpretive skills of the observing individuals.",
    },
    {
        "mechanicId": 2076,
        "name": "Grid Movement",
        "category": "Movement",
        "typical_game_category": "Miniatures",
        "description": "Pieces navigate across a playing surface divided into a uniform matrix of geometric shapes. Positional changes are constrained by this regular layout, requiring calculated steps along defined perpendicular or diagonal axes.",
    },
    {
        "mechanicId": 2078,
        "name": "Point to Point Movement",
        "category": "Movement",
        "typical_game_category": "Wargame",
        "description": "The playing area consists of distinct nodes connected by predefined pathways. Pieces may only travel between these specific locations by traversing the connected lines, ignoring the physical distance or empty space between them.",
    },
    {
        "mechanicId": 2080,
        "name": "Area Majority / Influence",
        "category": "Scoring",
        "typical_game_category": "Territory Building",
        "description": "Participants compete to maintain the greatest presence or control within specific bounded regions on the playing surface. Rewards are distributed periodically or at the end of the session based on who holds numerical superiority in each contested zone.",
    },
    {
        "mechanicId": 2081,
        "name": "Network and Route Building",
        "category": "Structural",
        "typical_game_category": "Trains",
        "description": "Participants construct continuous chains of components to connect distinct locations on the playing surface. Expanding these interconnected systems yields resources, points, or the ability to transport elements more efficiently.",
    },
    {
        "mechanicId": 2082,
        "name": "Worker Placement",
        "category": "Action",
        "typical_game_category": "Economic",
        "description": "Participants assign a limited pool of tokens to specific action spaces on a centralized board. Selecting a space typically restricts or prevents opponents from utilizing that same action until the tokens are retrieved.",
    },
    {
        "mechanicId": 2083,
        "name": "Constrained Bidding",
        "category": "Auction",
        "typical_game_category": "Economic",
        "description": "Participants compete for items by making offers, but the allowable values or the types of currency are heavily restricted by specific rules. These limitations force individuals to manage their resources within a strict framework rather than simply offering the highest possible amount.",
    },
    {
        "mechanicId": 2661,
        "name": "Push Your Luck",
        "category": "Action",
        "typical_game_category": "Card Game",
        "description": "Participants repeatedly decide whether to secure current gains or risk them for greater rewards by taking additional unpredictable actions. A negative outcome typically results in the loss of all progress accumulated during that specific turn.",
    },
    {
        "mechanicId": 2664,
        "name": "Deck, Bag, and Pool Building",
        "category": "Card",
        "typical_game_category": "Card Game",
        "description": "Participants start with a small, personalized set of components that they repeatedly draw from and cycle through during play. Throughout the session, individuals acquire new elements and remove weaker ones to optimize the overall quality and efficiency of their personal collection.",
    },
    {
        "mechanicId": 2689,
        "name": "Action Queue",
        "category": "Action",
        "typical_game_category": "Science Fiction",
        "description": "Participants plan a sequence of specific commands in advance by placing them in a structured line or row. These chosen commands are then resolved strictly in the order they were placed, requiring careful foresight to ensure earlier actions do not invalidate later ones.",
    },
    {
        "mechanicId": 2813,
        "name": "Rondel",
        "category": "Action",
        "typical_game_category": "Economic",
        "description": "Available options are arranged in a circular track, and participants move a pawn around this loop to select their actions. Advancing a short distance is typically free, while jumping further ahead requires spending resources, limiting the ability to perform the same action repeatedly.",
    },
    {
        "mechanicId": 2819,
        "name": "Solo / Solitaire Game",
        "category": "Structural",
        "typical_game_category": "Wargame",
        "description": "The system is designed to be fully playable by a single individual, often featuring automated opponents or specific win conditions to overcome. The participant competes against the inherent challenges of the rule set rather than human opponents.",
    },
    {
        "mechanicId": 2821,
        "name": "Single Loser Game",
        "category": "Structural",
        "typical_game_category": "Card Game",
        "description": "Multiple participants compete to avoid being the solitary defeated individual at the end of the session. As soon as one participant meets the predefined failure condition, the session ends, and all remaining individuals are collectively declared the winners.",
    },
    {
        "mechanicId": 2828,
        "name": "Turn Order: Progressive",
        "category": "Turn Order",
        "typical_game_category": "Economic",
        "description": "A designated token marks the starting individual for a given round, with subsequent actions proceeding sequentially around the table. At the end of the round, this token is passed to the next adjacent participant, ensuring that the starting position rotates evenly throughout the session.",
    },
    {
        "mechanicId": 2835,
        "name": "Passed Action Token",
        "category": "Turn Order",
        "typical_game_category": "Science Fiction",
        "description": "A physical marker is given to an individual, granting them the immediate ability to perform a specific action or take a turn. Once used, the marker is handed to another participant according to the system's rules, dictating who acts next rather than following a strict seating order.",
    },
    {
        "mechanicId": 2836,
        "name": "Lose a Turn",
        "category": "Turn Order",
        "typical_game_category": "Card Game",
        "description": "An individual is entirely skipped during the normal sequence of play as a penalty or consequence of an event. They may not perform any actions or decisions during this skipped phase, forcing them to wait until the rotation reaches them again.",
    },
    {
        "mechanicId": 2837,
        "name": "Programmed Movement",
        "category": "Movement",
        "typical_game_category": "Wargame",
        "description": "Participants secretly plan their exact path of travel several steps in advance using concealed components. Once all plans are locked in, they are revealed and executed sequentially, often leading to unpredictable interactions as pieces bump into one another or move out of the anticipated path.",
    },
    {
        "mechanicId": 2838,
        "name": "Scenario / Mission / Campaign Game",
        "category": "Structural",
        "typical_game_category": "Wargame",
        "description": "The session is played using a specific narrative setup or rule variant selected from a larger provided collection. These setups can be played as standalone experiences or linked together sequentially, where the outcome of one session influences the starting conditions of the next.",
    },
    {
        "mechanicId": 2839,
        "name": "Movement Points",
        "category": "Movement",
        "typical_game_category": "Wargame",
        "description": "Participants receive a specific allowance of values each turn dedicated exclusively to traversing the playing surface. Different terrains, elevations, or pathways require expending varying amounts of these values, forcing careful calculation of the most efficient route.",
    },
    {
        "mechanicId": 2840,
        "name": "Action/Event",
        "category": "Action",
        "typical_game_category": "Wargame",
        "description": "Participants are presented with components that offer two distinct, mutually exclusive options: taking standard procedural actions or triggering a specialized unique effect. Choosing one option inherently forfeits the other, forcing individuals to constantly weigh immediate tactical needs against powerful situational benefits.",
    },
    {
        "mechanicId": 2841,
        "name": "Highest-Lowest Scoring",
        "category": "Scoring",
        "typical_game_category": "Economic",
        "description": "Participants track multiple distinct sets of points or resources throughout the session. During the final evaluation, an individual's overall standing is determined solely by the value of their weakest or lowest-scoring category, requiring balanced progression across all areas.",
    },
    {
        "mechanicId": 2842,
        "name": "Score-and-Reset Game",
        "category": "Structural",
        "typical_game_category": "Card Game",
        "description": "The session is divided into distinct rounds where participants accumulate points or advantages over a series of actions. At the conclusion of the round, the board state or accumulated hands are cleared, and a new round begins from a neutral starting position while retaining the overall scores.",
    },
    {
        "mechanicId": 2843,
        "name": "Map Addition",
        "category": "Structural",
        "typical_game_category": "Exploration",
        "description": "The physical playing surface expands during the session as new terrain tiles or boards are placed adjacent to existing ones. This gradual revelation forces participants to adapt their spatial strategies as the boundaries and available pathways of the environment continuously grow.",
    },
    {
        "mechanicId": 2844,
        "name": "Secret Unit Deployment",
        "category": "Other",
        "typical_game_category": "Wargame",
        "description": "Participants place their pieces onto the playing surface with their exact identities, strengths, or types hidden from opponents. The true nature of these pieces is only revealed when they engage in conflict or when specific conditions force them to be exposed.",
    },
    {
        "mechanicId": 2845,
        "name": "Increase Value of Unchosen Resources",
        "category": "Resource",
        "typical_game_category": "Economic",
        "description": "Items, actions, or currencies that remain unselected by participants during a round gradually accumulate additional benefits over time. This incentivizes individuals to eventually select previously ignored options once the accumulated bonus outweighs the initial lack of appeal.",
    },
    {
        "mechanicId": 2846,
        "name": "Once-Per-Game Abilities",
        "category": "Action",
        "typical_game_category": "Fantasy",
        "description": "Participants possess a powerful, unique action or advantage that can only be activated a single time during the entire session. Deciding exactly when to trigger this irreversible effect is a critical strategic consideration.",
    },
    {
        "mechanicId": 2847,
        "name": "Advantage Token",
        "category": "Action",
        "typical_game_category": "Economic",
        "description": "A specific physical marker grants its holder a persistent benefit, rule exception, or tie-breaking priority. The marker can change ownership throughout the session based on specific triggers, temporarily shifting this distinct edge to different individuals.",
    },
    {
        "mechanicId": 2848,
        "name": "Take That",
        "category": "Action",
        "typical_game_category": "Card Game",
        "description": "Participants utilize specific actions or play components with the direct intention of hindering, penalizing, or destroying the progress of their opponents. The interactions are explicitly aggressive and targeted, often resulting in immediate negative consequences for the chosen victim.",
    },
    {
        "mechanicId": 2849,
        "name": "Team-Based Game",
        "category": "Structural",
        "typical_game_category": "Card Game",
        "description": "Participants are divided into distinct factions or partnerships, working together to achieve a shared victory condition. Success requires coordination and communication among allies to outmaneuver the opposing factions.",
    },
    {
        "mechanicId": 2850,
        "name": "Events",
        "category": "Structural",
        "typical_game_category": "Wargame",
        "description": "The system periodically introduces external occurrences that alter the rules, board state, or available resources for all participants. These occurrences happen independently of participant choices, requiring them to constantly adapt their strategies to changing global conditions.",
    },
    {
        "mechanicId": 2851,
        "name": "Campaign / Battle Card Driven",
        "category": "Card",
        "typical_game_category": "Wargame",
        "description": "Participants use a hand of specialized components to dictate all aspects of their strategy, from mobilizing forces to triggering occurrences. The entire flow of the conflict is dictated by how and when these components are played, rather than relying on a fixed sequence of standard actions.",
    },
    {
        "mechanicId": 2852,
        "name": "Tech Trees / Tech Tracks",
        "category": "Structural",
        "typical_game_category": "Economic",
        "description": "Participants invest resources or actions to advance along a branching or linear progression system. Progressing further along these pathways unlocks new permanent abilities, improved actions, or victory points for the individual.",
    },
    {
        "mechanicId": 2853,
        "name": "Turn Order: Stat-Based",
        "category": "Turn Order",
        "typical_game_category": "Economic",
        "description": "The sequence in which individuals take their actions is determined by a specific numerical value or attribute belonging to their pieces or faction. This sequence dynamically changes as the underlying statistics increase or decrease during play.",
    },
    {
        "mechanicId": 2854,
        "name": "Player Judge",
        "category": "Social",
        "typical_game_category": "Party Game",
        "description": "One participant temporarily assumes the role of an arbiter to evaluate the subjective submissions or performances of the other individuals. The arbiter selects a winner for that round based on personal preference, after which the evaluating role typically rotates to the next participant.",
    },
    {
        "mechanicId": 2855,
        "name": "Ratio / Combat Results Table",
        "category": "Other",
        "typical_game_category": "Wargame",
        "description": "Outcomes of conflicts are resolved by comparing the relative numerical strengths of the opposing sides to create a mathematical proportion. This ratio is then cross-referenced with a randomizer roll on a standardized matrix to determine the exact casualties or effects.",
    },
    {
        "mechanicId": 2856,
        "name": "Square Grid",
        "category": "Structural",
        "typical_game_category": "Wargame",
        "description": "The playing surface is divided into a uniform network of four-sided spaces arranged in intersecting rows and columns. Movement and spatial relationships are strictly governed by this orthogonal layout, often allowing travel across shared borders and sometimes diagonals.",
    },
    {
        "mechanicId": 2857,
        "name": "Stat Check Resolution",
        "category": "Other",
        "typical_game_category": "Fantasy",
        "description": "Outcomes of attempted actions are determined by comparing a randomized value against a predefined numerical attribute associated with a participant's character or unit. Success requires the generated number to meet or exceed a target threshold that is modified by the relevant attribute.",
    },
    {
        "mechanicId": 2858,
        "name": "Action Timer",
        "category": "Action",
        "typical_game_category": "Real-time",
        "description": "Participants must complete their decisions or execute specific tasks within a strict, real-time limit imposed by a physical or digital clock. Failure to finish before the limit expires typically results in a loss of opportunity or a penalty.",
    },
    {
        "mechanicId": 2859,
        "name": "Auction: English",
        "category": "Auction",
        "typical_game_category": "Economic",
        "description": "Participants compete for an item by openly declaring increasingly higher offers in real-time or in sequence. The process concludes when no individual is willing to surpass the current highest offer, securing the item for that final participant.",
    },
    {
        "mechanicId": 2860,
        "name": "Auction: Sealed Bid",
        "category": "Auction",
        "typical_game_category": "Card Game",
        "description": "Participants simultaneously submit a single, hidden offer for a contested item or advantage. All submissions are revealed concurrently, and the individual with the highest offer pays their proposed amount to secure the prize.",
    },
    {
        "mechanicId": 2861,
        "name": "Auction: Turn Order Until Pass",
        "category": "Auction",
        "typical_game_category": "Card Game",
        "description": "Participants take turns making incrementally higher offers for an item following a strict sequential order. Individuals may drop out at any time, but once they decline to increase the offer, they are permanently removed from that specific competition.",
    },
    {
        "mechanicId": 2862,
        "name": "Crayon Rail System",
        "category": "Movement",
        "typical_game_category": "Trains",
        "description": "Participants use erasable writing utensils to physically draw transportation routes directly onto a laminated playing surface. These customized pathways connect various locations and are utilized to move goods or pieces across the map.",
    },
    {
        "mechanicId": 2863,
        "name": "Minimap Resolution",
        "category": "Structural",
        "typical_game_category": "Wargame",
        "description": "Complex interactions or conflicts that occur on the primary playing surface are resolved by transitioning the involved pieces to a separate, magnified representation of that specific location. This allows for detailed tactical maneuvering before the final outcome is applied back to the main board.",
    },
    {
        "mechanicId": 2864,
        "name": "Multiple Maps",
        "category": "Structural",
        "typical_game_category": "Fantasy",
        "description": "The physical playing area consists of two or more distinct spatial representations that operate concurrently. Participants must manage their presence and actions across these separate environments, often moving elements between them or balancing strategic priorities on different boards.",
    },
    {
        "mechanicId": 2865,
        "name": "Hidden Roles",
        "category": "Social",
        "typical_game_category": "Bluffing",
        "description": "Participants are secretly assigned to specific alignments, teams, or character identities at the beginning of the session. Individuals must deduce the allegiances of others through their actions while concealing their own true objectives until the conclusion of play.",
    },
    {
        "mechanicId": 2866,
        "name": "Flicking",
        "category": "Action",
        "typical_game_category": "Action / Dexterity",
        "description": "Participants propel physical components across the playing surface by striking them sharply with their fingers. Success relies on manual dexterity and physical precision to hit targets, navigate obstacles, or position pieces advantageously.",
    },
    {
        "mechanicId": 2867,
        "name": "Connections",
        "category": "Structural",
        "typical_game_category": "Trains",
        "description": "Participants place components to establish continuous links between specific predefined points on the playing surface. Achieving these uninterrupted pathways often yields resources, victory points, or the completion of private objectives.",
    },
    {
        "mechanicId": 2868,
        "name": "Paper-and-Pencil",
        "category": "Structural",
        "typical_game_category": "Dice",
        "description": "Participants use writing instruments to record information, track resources, or map out spatial layouts on personal sheets throughout the session. The physical marking of these consumable sheets serves as the primary method of tracking individual progress and board state.",
    },
    {
        "mechanicId": 2869,
        "name": "Line Drawing",
        "category": "Action",
        "typical_game_category": "Party Game",
        "description": "Participants use writing tools to create continuous physical marks on the playing surface to define boundaries, routes, or areas of effect. The precise geometry and length of these drawn elements directly impact spatial interactions and scoring.",
    },
    {
        "mechanicId": 2870,
        "name": "Tug of War",
        "category": "Structural",
        "typical_game_category": "Wargame",
        "description": "Participants compete to shift a shared marker along a linear track toward their respective sides by applying resources or winning conflicts. Victory or advantages are secured when an individual successfully pulls the marker to their designated end of the track.",
    },
    {
        "mechanicId": 2871,
        "name": "Pattern Movement",
        "category": "Movement",
        "typical_game_category": "Abstract Strategy",
        "description": "Pieces navigate the playing surface according to strict, predefined geometric shapes or directional rules unique to each unit type. This forces participants to carefully calculate spatial alignments and anticipate where specific pieces can land on future turns.",
    },
    {
        "mechanicId": 2872,
        "name": "Static Capture",
        "category": "Action",
        "typical_game_category": "Abstract Strategy",
        "description": "Participants remove opposing pieces from the playing surface without entering the physical space occupied by the target. This typically involves surrounding the enemy piece or placing a unit in a specific adjacent configuration to eliminate the threat.",
    },
    {
        "mechanicId": 2873,
        "name": "Selection Order Bid",
        "category": "Auction",
        "typical_game_category": "Economic",
        "description": "Participants offer resources or currency to determine the sequence in which they will choose from a shared pool of available items or roles. The highest offer guarantees the first choice, allowing individuals to prioritize critical selections over raw resource conservation.",
    },
    {
        "mechanicId": 2874,
        "name": "Different Dice Movement",
        "category": "Movement",
        "typical_game_category": "Racing",
        "description": "Participants advance pieces along a path by utilizing varied sets of physical randomizers, often featuring distinct numerical distributions or symbols. The choice of which specific randomizers to roll directly alters the probability of reaching destinations or avoiding hazards.",
    },
    {
        "mechanicId": 2875,
        "name": "Chaining",
        "category": "Action",
        "typical_game_category": "Medieval",
        "description": "Participants execute an initial action or play a component that immediately permits the execution of subsequent, often related, actions. This creates a cascading sequence of effects from a single initial trigger, maximizing efficiency within a turn.",
    },
    {
        "mechanicId": 2876,
        "name": "Multiple-Lot Auction",
        "category": "Auction",
        "typical_game_category": "Economic",
        "description": "Participants submit offers on several distinct items or groupings simultaneously rather than resolving them one at a time. This requires individuals to distribute their resources across various potential acquisitions and evaluate the relative worth of concurrent opportunities.",
    },
    {
        "mechanicId": 2877,
        "name": "Critical Hits and Failures",
        "category": "Dice",
        "typical_game_category": "Wargame",
        "description": "Specific extreme results generated by a randomizer trigger exceptionally positive or catastrophically negative outcomes that bypass standard resolution rules. This introduces a small degree of high-stakes unpredictability, ensuring that even highly probable tasks carry some risk or chance for extraordinary success.",
    },
    {
        "mechanicId": 2878,
        "name": "Line of Sight",
        "category": "Movement",
        "typical_game_category": "Wargame",
        "description": "Interactions between pieces require an unobstructed geometric path across the playing surface to a designated target. Obstacles, terrain features, or other units that intersect this straight path block the interaction, demanding careful spatial positioning.",
    },
    {
        "mechanicId": 2879,
        "name": "Time Track",
        "category": "Turn Order",
        "typical_game_category": "Adventure",
        "description": "Participants spend temporal units rather than standard resources to perform actions, advancing their marker along a linear path representing time. The individual whose marker is currently furthest behind on this path consistently takes the next turn, allowing for consecutive actions if they remain in last place.",
    },
    {
        "mechanicId": 2880,
        "name": "Zone of Control",
        "category": "Movement",
        "typical_game_category": "Wargame",
        "description": "Individual pieces exert influence over the spaces immediately adjacent to their current location on the playing surface. Entering or leaving these influenced areas typically imposes movement penalties, forces conflict, or restricts the available actions of opposing pieces.",
    },
    {
        "mechanicId": 2882,
        "name": "End Game Bonuses",
        "category": "Scoring",
        "typical_game_category": "Economic",
        "description": "Participants are awarded additional victory points or rewards only after the primary session has concluded, based on specific criteria or accumulated assets. These deferred rewards often shift the final standings and encourage long-term strategic planning that may not yield immediate benefits.",
    },
    {
        "mechanicId": 2883,
        "name": "Area-Impulse",
        "category": "Action",
        "typical_game_category": "Wargame",
        "description": "The playing surface is divided into discrete zones, and participants take turns activating an entire zone rather than individual pieces. Once a zone is activated, all pieces within it may perform their actions, after which the zone is typically marked as exhausted for the remainder of the phase.",
    },
    {
        "mechanicId": 2884,
        "name": "Sudden Death Ending",
        "category": "Structural",
        "typical_game_category": "Fantasy",
        "description": "The session concludes immediately the moment a specific, predefined condition is met by any participant or game state. This abrupt termination bypasses any remaining turns or planned rounds, making the timing of the conclusion unpredictable and highly tactical.",
    },
    {
        "mechanicId": 2885,
        "name": "Measurement Movement",
        "category": "Movement",
        "typical_game_category": "Wargame",
        "description": "Pieces travel across an open playing surface without a grid by using rulers, templates, or tape measures to determine exact physical distances. This analog approach allows for precise angling and positioning, relying on physical geometry rather than discrete spaces.",
    },
    {
        "mechanicId": 2886,
        "name": "Resource to Move",
        "category": "Movement",
        "typical_game_category": "Racing",
        "description": "Participants must expend specific collected assets, such as currency or goods, to change the location of their pieces on the playing surface. This economic constraint forces individuals to balance the logistical cost of transportation against other tactical uses for their accumulated assets.",
    },
    {
        "mechanicId": 2887,
        "name": "Catch the Leader",
        "category": "Other",
        "typical_game_category": "Economic",
        "description": "The system dynamically introduces penalties for the individual currently in first place or provides compensatory advantages to those trailing behind. These built-in equalizing mechanisms prevent a single participant from securing an insurmountable advantage early in the session.",
    },
    {
        "mechanicId": 2888,
        "name": "Mancala",
        "category": "Action",
        "typical_game_category": "Abstract Strategy",
        "description": "Participants collect all tokens from a single location and distribute them sequentially, dropping one token at a time into adjacent spaces along a predefined path. The final token's landing location often triggers specific actions, rewards, or further distribution chains.",
    },
    {
        "mechanicId": 2889,
        "name": "Real-Time",
        "category": "Action",
        "typical_game_category": "Science Fiction",
        "description": "Participants execute actions continuously and simultaneously without adhering to a structured turn sequence. Decisions and physical movements are made as quickly as possible, governed by an overarching timer or the speed at which individuals can process information.",
    },
    {
        "mechanicId": 2890,
        "name": "Victory Points as a Resource",
        "category": "Resource",
        "typical_game_category": "Economic",
        "description": "The same metric used to determine the final winner can be permanently spent during the session to acquire immediate benefits, units, or actions. Participants must constantly weigh the value of temporary tactical advantages against the permanent reduction of their final score.",
    },
    {
        "mechanicId": 2891,
        "name": "Kill Steal",
        "category": "Action",
        "typical_game_category": "Fighting",
        "description": "Participants have the opportunity to deliver the final, decisive strike against a target that opponents have already weakened. The individual who secures this finishing blow claims the entirety of the reward, capitalizing on the expended effort and resources of others.",
    },
    {
        "mechanicId": 2892,
        "name": "Hidden Movement",
        "category": "Movement",
        "typical_game_category": "Deduction",
        "description": "One or more participants traverse the playing area without visually updating their pieces on the shared board, instead recording their coordinates secretly. Opponents must use deduction and localized clues to pinpoint these concealed locations.",
    },
    {
        "mechanicId": 2893,
        "name": "Deck Construction",
        "category": "Card",
        "typical_game_category": "Card Game",
        "description": "Participants assemble a customized set of components before the session begins, selecting from a vast overarching pool of available options. This preparation phase allows individuals to design specific synergies and strategies that they will pilot during actual gameplay.",
    },
    {
        "mechanicId": 2894,
        "name": "Interrupts",
        "category": "Action",
        "typical_game_category": "Card Game",
        "description": "Participants possess the ability to halt or alter the progression of an opponent's turn by immediately playing a specific component or ability. This reactive mechanism forces the active individual to resolve the sudden interference before continuing with their intended sequence of actions.",
    },
    {
        "mechanicId": 2895,
        "name": "Action Drafting",
        "category": "Action",
        "typical_game_category": "Economic",
        "description": "Participants sequentially select their desired maneuvers from a shared, limited pool of available options. Once an option is chosen by an individual, it is typically removed from the pool or becomes significantly more expensive for subsequent participants to select during that round.",
    },
    {
        "mechanicId": 2896,
        "name": "Turn Order: Role Order",
        "category": "Turn Order",
        "typical_game_category": "Card Game",
        "description": "The sequence in which individuals act is dictated by the specific character, profession, or role they have adopted for that round. Each available role is assigned a strict priority number or position, inherently weaving the timing of a turn into the strategic selection of the role itself.",
    },
    {
        "mechanicId": 2897,
        "name": "Variable Setup",
        "category": "Structural",
        "typical_game_category": "Economic",
        "description": "The initial conditions of the session, such as component placement, available resources, or objective locations, are randomized or selected differently before play begins. This ensures that the starting environment presents a distinct puzzle and requires divergent opening strategies for every session.",
    },
    {
        "mechanicId": 2898,
        "name": "Prisoner's Dilemma",
        "category": "Social",
        "typical_game_category": "Negotiation",
        "description": "Participants simultaneously make a choice between cooperating with opponents or betraying them for personal gain. While mutual cooperation yields a moderately positive outcome for both, betraying a cooperative opponent yields the highest individual reward, creating a tense psychological standoff.",
    },
    {
        "mechanicId": 2899,
        "name": "Track Movement",
        "category": "Movement",
        "typical_game_category": "Economic",
        "description": "Pieces move along a linear or branching path with specific, discrete steps. Movement is constrained entirely to this predefined track rather than an open grid or traversable area.",
    },
    {
        "mechanicId": 2900,
        "name": "Market",
        "category": "Resource",
        "typical_game_category": "Economic",
        "description": "A central display of available items, resources, or components is established for participants to acquire. The selection fluctuates as items are purchased and replaced, often featuring dynamic pricing based on supply and demand.",
    },
    {
        "mechanicId": 2901,
        "name": "Movement Template",
        "category": "Movement",
        "typical_game_category": "Wargame",
        "description": "Physical guides or tools are placed on the playing surface to determine the exact distance and trajectory a piece can travel. The piece is relocated from one end of the tool to the other, ensuring precise analog positioning without relying on grids.",
    },
    {
        "mechanicId": 2902,
        "name": "Three Dimensional Movement",
        "category": "Movement",
        "typical_game_category": "Wargame",
        "description": "Pieces navigate a playing space that incorporates verticality as well as standard horizontal axes. Spatial relationships and travel rules explicitly account for depth, height, and overlapping elevations during play.",
    },
    {
        "mechanicId": 2903,
        "name": "Auction: Dexterity",
        "category": "Auction",
        "typical_game_category": "Real-time",
        "description": "Participants compete for items by performing physical tasks of skill, balance, or precision rather than bidding currency. The individual who successfully completes the physical challenge or outperforms others secures the contested asset.",
    },
    {
        "mechanicId": 2904,
        "name": "Slide/Push",
        "category": "Action",
        "typical_game_category": "Renaissance",
        "description": "Participants insert new components into a grid or track, forcing existing pieces to shift into adjacent spaces. This physical displacement actively changes board configurations, alters pathways, or pushes pieces completely off the playing surface.",
    },
    {
        "mechanicId": 2905,
        "name": "Map Reduction",
        "category": "Structural",
        "typical_game_category": "Abstract Strategy",
        "description": "The available playing surface actively shrinks during the session as physical sections are removed or rendered impassable. This forces participants into closer proximity, limiting spatial options and escalating conflict as the environment constricts.",
    },
    {
        "mechanicId": 2906,
        "name": "Auction: Dutch",
        "category": "Auction",
        "typical_game_category": "Economic",
        "description": "An item's price begins at an artificially high value and is incrementally lowered by a moderator or automated system. The first participant to accept the current price secures the item, instantly concluding the process.",
    },
    {
        "mechanicId": 2907,
        "name": "Auction: Dutch Priority",
        "category": "Auction",
        "typical_game_category": "Economic",
        "description": "Participants submit offers to establish a strict selection sequence for a set of available items. The individual with the highest offer pays their proposed amount and chooses first, followed sequentially by the remaining bidders until all items are claimed.",
    },
    {
        "mechanicId": 2908,
        "name": "Targeted Clues",
        "category": "Social",
        "typical_game_category": "Party Game",
        "description": "Participants provide hints or information explicitly directed at specific individuals rather than the entire group. This selective communication allows allies to coordinate or deduce solutions without broadcasting critical knowledge to opponents.",
    },
    {
        "mechanicId": 2909,
        "name": "Command Cards",
        "category": "Card",
        "typical_game_category": "Wargame",
        "description": "Participants utilize specific components that dictate exactly which units or geographical sectors can be activated during their turn. Playing one of these components strictly limits available actions to the depicted subset of forces or locations.",
    },
    {
        "mechanicId": 2910,
        "name": "Grid Coverage",
        "category": "Structural",
        "typical_game_category": "Puzzle",
        "description": "Participants place polyominoes or other geometric tiles onto a personal or shared board to completely fill specific shapes or zones. Success relies on spatial optimization to maximize covered areas while avoiding leaving empty spaces or covering restricted zones.",
    },
    {
        "mechanicId": 2911,
        "name": "Ownership",
        "category": "Structural",
        "typical_game_category": "Economic",
        "description": "Participants claim specific locations, units, or items on the playing surface, explicitly marking them as personal property. This possession typically grants exclusive rights to use the asset, collect revenue from it, or completely deny its use to opponents.",
    },
    {
        "mechanicId": 2912,
        "name": "Predictive Bid",
        "category": "Auction",
        "typical_game_category": "Card Game",
        "description": "Participants secretly commit resources or wagers based on what they anticipate opponents will do or the expected outcome of a future event. Rewards are distributed to those who accurately forecast the result or correctly anticipate opponent behavior.",
    },
    {
        "mechanicId": 2913,
        "name": "Bribery",
        "category": "Social",
        "typical_game_category": "Negotiation",
        "description": "Participants offer resources, currency, or favors to opponents in exchange for specific actions, inactions, or advantageous decisions. These transactions are often binding only by mutual agreement and rely on informal interpersonal negotiations rather than strict systemic rules.",
    },
    {
        "mechanicId": 2914,
        "name": "Card Play Conflict Resolution",
        "category": "Card",
        "typical_game_category": "Wargame",
        "description": "Outcomes of battles or contests are determined by participants selecting and revealing components from their hands rather than relying on randomized mechanisms. The numerical values, symbols, or text on the revealed components strictly dictate the victor and the specific consequences of the engagement.",
    },
    {
        "mechanicId": 2915,
        "name": "Negotiation",
        "category": "Social",
        "typical_game_category": "Bluffing",
        "description": "Participants verbally discuss terms to reach mutually beneficial agreements, trade resources, or resolve conflicts. Success relies heavily on persuasion, diplomacy, and effectively navigating the interpersonal dynamics of the group.",
    },
    {
        "mechanicId": 2916,
        "name": "Alliances",
        "category": "Social",
        "typical_game_category": "Negotiation",
        "description": "Participants formally or informally join forces to achieve mutual goals or overcome common adversaries during the session. These partnerships often require individuals to share resources or coordinate strategies while still maneuvering toward their own eventual victory.",
    },
    {
        "mechanicId": 2917,
        "name": "I Cut, You Choose",
        "category": "Action",
        "typical_game_category": "Card Game",
        "description": "One participant divides a set of items, resources, or components into distinct groupings. Another participant then selects which of the available groupings they wish to take, forcing the divider to create evenly balanced options to avoid leaving themselves with an inferior share.",
    },
    {
        "mechanicId": 2918,
        "name": "Die Icon Resolution",
        "category": "Dice",
        "typical_game_category": "Fantasy",
        "description": "The outcomes of physical randomizers are determined by specific symbols rather than standard numerical values. These symbols map directly to specific actions, damage types, or effects, bypassing the need to consult mathematical tables or calculate totals.",
    },
    {
        "mechanicId": 2919,
        "name": "Turn Order: Random",
        "category": "Turn Order",
        "typical_game_category": "Wargame",
        "description": "The sequence in which individuals take their actions is determined entirely by chance at the start of each round or turn. This unpredictability prevents participants from relying on fixed rotational sequences and forces constant tactical adaptation.",
    },
    {
        "mechanicId": 2920,
        "name": "Elapsed Real Time Ending",
        "category": "Structural",
        "typical_game_category": "Real-time",
        "description": "The session concludes automatically when a predetermined physical duration expires, regardless of the current board state or the number of turns taken. This imposes a strict global time limit, creating urgency and forcing participants to optimize their actions within a fixed window.",
    },
    {
        "mechanicId": 2921,
        "name": "Melding and Splaying",
        "category": "Card",
        "typical_game_category": "Card Game",
        "description": "Participants arrange components in overlapping columns or rows, partially covering previously played elements while leaving specific icons or text visible. This precise spatial arrangement dictates which abilities are currently active and how new additions interact with the established sequence.",
    },
    {
        "mechanicId": 2922,
        "name": "Singing",
        "category": "Social",
        "typical_game_category": "Party Game",
        "description": "Participants use vocal musical performance to convey information, fulfill objectives, or interact with the system. Success typically relies on pitch accuracy, lyric recall, or the subjective judgment of opponents regarding the performance.",
    },
    {
        "mechanicId": 2923,
        "name": "Roles with Asymmetric Information",
        "category": "Social",
        "typical_game_category": "Deduction",
        "description": "Participants are assigned specific identities or positions that grant them exclusive knowledge unavailable to the rest of the group. This uneven distribution of information forces individuals to deduce the motives of others while carefully managing what they reveal about their own knowledge.",
    },
    {
        "mechanicId": 2924,
        "name": "Traitor Game",
        "category": "Social",
        "typical_game_category": "Bluffing",
        "description": "One or more participants secretly operate against the shared objectives of the larger group while pretending to cooperate. The hidden adversaries attempt to sabotage the collective effort from within, requiring the loyal majority to deduce their identities before the group fails.",
    },
    {
        "mechanicId": 2925,
        "name": "Bias",
        "category": "Other",
        "typical_game_category": "Science Fiction",
        "description": "Pieces automatically move in a certain direction, or it is easier to move in a certain direction, or some directional or environmental vector has gameplay effects. This is commonly used to simulate wind, currents, gravity, conveyor belts, sun angle, or other environmental features.",
    },
    {
        "mechanicId": 2926,
        "name": "Moving Multiple Units",
        "category": "Movement",
        "typical_game_category": "Wargame",
        "description": "Participants are permitted or required to change the locations of several distinct pieces during a single turn or action phase. This allows for coordinated maneuvers, formation shifting, and broader spatial repositioning across the playing surface simultaneously.",
    },
    {
        "mechanicId": 2927,
        "name": "Stacking and Balancing",
        "category": "Action",
        "typical_game_category": "Action / Dexterity",
        "description": "Participants physically place components on top of one another to build vertical structures without causing them to collapse. Success relies heavily on fine motor skills, spatial awareness, and an understanding of physical gravity and equilibrium.",
    },
    {
        "mechanicId": 2928,
        "name": "Communication Limits",
        "category": "Social",
        "typical_game_category": "Card Game",
        "description": "The system imposes strict rules on how, when, or what information participants are allowed to share with one another. These restrictions prevent open coordination, forcing individuals to rely on intuition, non-verbal cues, or deducing intentions through gameplay actions.",
    },
    {
        "mechanicId": 2929,
        "name": "Map Deformation",
        "category": "Structural",
        "typical_game_category": "Fantasy",
        "description": "The physical playing surface undergoes permanent or temporary physical alterations that change its topography, connections, or boundaries during play. Participants must constantly adapt their spatial strategies as the fundamental geography of the environment shifts.",
    },
    {
        "mechanicId": 2930,
        "name": "Re-rolling and Locking",
        "category": "Dice",
        "typical_game_category": "Dice",
        "description": "Participants generate a set of randomized results and may choose to keep specific outcomes while generating new values for the remainder. This process often repeats over several iterations, allowing individuals to push their luck in pursuit of optimal combinations.",
    },
    {
        "mechanicId": 2931,
        "name": "Loans",
        "category": "Resource",
        "typical_game_category": "Economic",
        "description": "Participants acquire an immediate influx of currency or assets with the binding obligation to repay a larger amount at a later stage. Failure to meet these repayment obligations typically incurs severe penalties, forcing a careful balance between immediate capital needs and future liabilities.",
    },
    {
        "mechanicId": 2932,
        "name": "Delayed Purchase",
        "category": "Resource",
        "typical_game_category": "Card Game",
        "description": "Participants commit resources to acquire an asset, but the item does not become available for use until a specified amount of time or turns has passed. This requires anticipatory planning, as the benefits of the expenditure are entirely deferred.",
    },
    {
        "mechanicId": 2933,
        "name": "Speed Matching",
        "category": "Action",
        "typical_game_category": "Real-time",
        "description": "Participants simultaneously attempt to identify and claim components that share specific characteristics with a target object as quickly as possible. Success relies entirely on rapid visual processing and faster physical reflexes than the opponents.",
    },
    {
        "mechanicId": 2934,
        "name": "Impulse Movement",
        "category": "Movement",
        "typical_game_category": "Science Fiction",
        "description": "The movement phase is broken down into multiple smaller segments, during which pieces may travel only a fraction of their total allowance. This granular approach allows participants to react to shifting positions and intercept opponents before a full movement cycle is completed.",
    },
    {
        "mechanicId": 2935,
        "name": "Move Through Deck",
        "category": "Card",
        "typical_game_category": "Card Game",
        "description": "Participants cycle through a stack of components to find specific elements, trigger occurrences, or measure the passage of time. The session or a specific phase often ends when the stack is completely depleted, making the physical pile a pacing mechanism.",
    },
    {
        "mechanicId": 2936,
        "name": "Turn Order: Claim Action",
        "category": "Turn Order",
        "typical_game_category": "Economic",
        "description": "Participants determine the sequence of play for an upcoming round by explicitly selecting a position from available options on the board. Choosing an earlier position often means sacrificing immediate tactical advantages or resources in exchange for future priority.",
    },
    {
        "mechanicId": 2937,
        "name": "Matching",
        "category": "Other",
        "typical_game_category": "Card Game",
        "description": "Participants seek to identify or pair components that share identical symbols, shapes, or attributes from a larger pool. Achieving these identical pairings typically yields rewards or allows for the removal of the paired elements from the playing area.",
    },
    {
        "mechanicId": 2938,
        "name": "Semi-Cooperative Game",
        "category": "Structural",
        "typical_game_category": "Adventure",
        "description": "Participants must work together to overcome a shared threat or system challenge while simultaneously pursuing their own individual victory conditions. If the collective effort fails, all individuals lose, but if successful, only the participant with the highest personal score is declared the winner.",
    },
    {
        "mechanicId": 2939,
        "name": "Physical Removal",
        "category": "Action",
        "typical_game_category": "Action / Dexterity",
        "description": "Participants manually extract components from a constructed physical structure without causing the remaining arrangement to collapse. This requires careful assessment of load-bearing elements and precise manual dexterity to safely dislodge the chosen piece.",
    },
    {
        "mechanicId": 2940,
        "name": "Pieces as Map",
        "category": "Structural",
        "typical_game_category": "Abstract Strategy",
        "description": "The physical components that participants manipulate or place also serve as the geographical terrain upon which the session takes place. As units or structures are added or moved, the layout and boundaries of the playing surface itself dynamically evolve.",
    },
    {
        "mechanicId": 2941,
        "name": "Follow",
        "category": "Action",
        "typical_game_category": "Economic",
        "description": "When an active individual selects a specific action, opponents are given the immediate opportunity to perform a similar, often weaker, version of that same action out of turn. This keeps all participants engaged constantly and forces the active individual to consider how their choices benefit others.",
    },
    {
        "mechanicId": 2942,
        "name": "Cube Tower",
        "category": "Other",
        "typical_game_category": "Territory Building",
        "description": "Participants drop wooden or plastic blocks into a three-dimensional hollow structure containing internal baffles. The randomized output of blocks that successfully tumble out the bottom determines the outcome of conflicts or events, while retained blocks alter future probabilities.",
    },
    {
        "mechanicId": 2943,
        "name": "Finale Ending",
        "category": "Structural",
        "typical_game_category": "Science Fiction",
        "description": "The conclusion of the session triggers a distinct, separate phase with unique rules and mechanics that differ significantly from the primary gameplay. This final sequence serves as a climactic resolution, often requiring participants to utilize their accumulated resources in a final, decisive challenge.",
    },
    {
        "mechanicId": 2944,
        "name": "Turn Order: Auction",
        "category": "Turn Order",
        "typical_game_category": "Economic",
        "description": "Participants competitively bid resources or currency to determine the sequence in which they will act during the upcoming round. The highest bidder secures the most advantageous position in the sequence, forcing individuals to evaluate the economic cost of acting early.",
    },
    {
        "mechanicId": 2945,
        "name": "Induction",
        "category": "Other",
        "typical_game_category": "Deduction",
        "description": "Participants attempt to discover a hidden rule or pattern created by another individual or the system. They accomplish this by proposing examples and receiving feedback on whether those examples conform to the secret rule, gradually narrowing down the possibilities through logical inference.",
    },
    {
        "mechanicId": 2946,
        "name": "Auction: Fixed Placement",
        "category": "Auction",
        "typical_game_category": "Economic",
        "description": "Participants compete for items by placing their markers on specific, predefined spaces representing distinct monetary values. Once a space is occupied, opponents must typically place their markers on a higher available value to remain in contention, forcing the original occupant to relocate.",
    },
    {
        "mechanicId": 2947,
        "name": "Bingo",
        "category": "Other",
        "typical_game_category": "Dice",
        "description": "A central system randomly generates numbers, symbols, or conditions that all participants simultaneously cross-reference against their personal grids or boards. The objective is to be the first to mark a specific predetermined pattern across the grid based on the called elements.",
    },
    {
        "mechanicId": 2948,
        "name": "Order Counters",
        "category": "Action",
        "typical_game_category": "Wargame",
        "description": "Participants issue commands to their units or regions by secretly placing physical markers representing specific tactical choices. Once all markers are placed, they are revealed and executed in a structured sequence, requiring individuals to anticipate opponent strategies during the planning phase.",
    },
    {
        "mechanicId": 2949,
        "name": "Contracts",
        "category": "Scoring",
        "typical_game_category": "Economic",
        "description": "Participants acquire specific, predefined objectives that require the collection and submission of exact combinations of resources or assets. Successfully fulfilling these requirements yields immediate rewards, currency, or victory points based on the difficulty of the requested combination.",
    },
    {
        "mechanicId": 2950,
        "name": "Layering",
        "category": "Structural",
        "typical_game_category": "Card Game",
        "description": "Participants physically place new components over existing ones on the playing surface, partially or completely obscuring the elements underneath. The visible attributes of the topmost components dictate the current rules, resources, or abilities, allowing the play area to evolve dynamically.",
    },
    {
        "mechanicId": 2951,
        "name": "Drafting",
        "category": "Action",
        "typical_game_category": "Card Game",
        "description": "Participants take turns selecting individual items from a shared, face-up pool of available options. This transparent selection process allows individuals to acquire necessary resources while simultaneously observing and potentially denying items desired by opponents.",
    },
    {
        "mechanicId": 2952,
        "name": "Action Retrieval",
        "category": "Action",
        "typical_game_category": "Fantasy",
        "description": "Participants expend specific components from their personal supply to perform corresponding actions, rendering those options temporarily unavailable. To regain access to these expended choices, the individual must dedicate a subsequent turn or action specifically to recovering all previously used components.",
    },
    {
        "mechanicId": 2953,
        "name": "Turn Order: Pass Order",
        "category": "Turn Order",
        "typical_game_category": "Economic",
        "description": "The sequence in which individuals take their actions in the upcoming round is determined strictly by when they choose to conclude their current round. Participants who opt to end their participation early secure an earlier position in the sequence for the next phase of play.",
    },
    {
        "mechanicId": 2954,
        "name": "Relative Movement",
        "category": "Movement",
        "typical_game_category": "Card Game",
        "description": "The positional changes of pieces on the playing surface are calculated in relation to other moving elements rather than fixed geographical points. This often represents shifting environments, physical physics, or independently moving platforms where spatial relationships constantly fluctuate.",
    },
    {
        "mechanicId": 2955,
        "name": "Worker Placement, Different Worker Types",
        "category": "Action",
        "typical_game_category": "Economic",
        "description": "Participants assign a limited pool of tokens to central action spaces, but these tokens possess distinct classifications or abilities. The specific type of token deployed dictates which spaces can be legally chosen or alters the efficiency and outcome of the resulting action.",
    },
    {
        "mechanicId": 2956,
        "name": "Worker Placement with Dice Workers",
        "category": "Action",
        "typical_game_category": "Dice",
        "description": "Participants utilize physical randomizers, such as dice, as their primary assignment tokens on a centralized board. The generated numerical values on these tokens restrict which specific action spaces can be legally selected or directly scale the potency of the chosen action.",
    },
    {
        "mechanicId": 2957,
        "name": "Automatic Resource Growth",
        "category": "Resource",
        "typical_game_category": "Economic",
        "description": "Specific action spaces, items, or locations accumulate additional assets or currency at the start of each round if they remain unselected. This compounding mechanism gradually increases the value of previously ignored options until a participant eventually claims the accumulated rewards.",
    },
    {
        "mechanicId": 2958,
        "name": "Narrative Choice / Paragraph",
        "category": "Structural",
        "typical_game_category": "Adventure",
        "description": "Participants navigate an unfolding story by reading designated sections of a provided text and making deliberate decisions based on the narrative context. These choices direct them to read entirely different sections of the text, branching the storyline and altering subsequent events and available options.",
    },
    {
        "mechanicId": 2959,
        "name": "King of the Hill",
        "category": "Scoring",
        "typical_game_category": "Fighting",
        "description": "Participants compete to occupy and maintain control over a highly contested, central focal point on the playing surface. Individuals are awarded points or significant advantages for each consecutive turn or round they successfully defend this prime location from opponent incursions.",
    },
    {
        "mechanicId": 2960,
        "name": "Force Commitment",
        "category": "Action",
        "typical_game_category": "Science Fiction",
        "description": "Participants must permanently or temporarily allocate a chosen quantity of their available assets to a specific conflict or objective. This requires evaluating the minimum investment needed for success while ensuring enough reserves remain for future actions and defenses.",
    },
    {
        "mechanicId": 2961,
        "name": "Legacy Game",
        "category": "Structural",
        "typical_game_category": "Fantasy",
        "description": "The physical components, rule set, and narrative of the system undergo permanent, irreversible changes across a linked series of sessions. Participants may be required to physically alter materials by placing stickers, destroying components, or writing directly on the playing surface, ensuring each copy of the product becomes entirely unique over time.",
    },
    {
        "mechanicId": 2980,
        "name": "Ladder Climbing",
        "category": "Card",
        "typical_game_category": "Card Game",
        "description": "Participants must play components from their hand that strictly exceed the value or complexity of the previously played set in the center of the table. The sequence continues until all opponents decline to play, allowing the last individual to clear the center and initiate a new sequence.",
    },
    {
        "mechanicId": 2987,
        "name": "Hidden Victory Points",
        "category": "Scoring",
        "typical_game_category": "Economic",
        "description": "The accumulated assets or objectives that determine the final winner are kept entirely concealed from opponents during play. This obscures the exact standings until the session concludes, forcing participants to make strategic decisions based on estimated rather than certain leads.",
    },
    {
        "mechanicId": 3000,
        "name": "Hot Potato",
        "category": "Action",
        "typical_game_category": "Card Game",
        "description": "A highly undesirable component or status effect is continually passed among participants, creating an atmosphere of urgency. The individual in possession of this element when a randomized timer expires or a specific trigger occurs suffers a severe penalty or elimination.",
    },
    {
        "mechanicId": 3005,
        "name": "Rock-Paper-Scissors",
        "category": "Action",
        "typical_game_category": "Card Game",
        "description": "Participants simultaneously choose from a limited set of options that interact in a cyclical hierarchy, where each choice defeats one alternative but is defeated by another. Success relies entirely on predicting opponent behavior and outmaneuvering their anticipated selections within this strict, balanced loop.",
    },
]
