export const communities = [
  { id: 1, name: 'Catan Lovers', 
    type: 'Public', 
    image: '/images/gameofthrones.png',
    description: 'A community for Catan enthusiasts.', 
    members: 9 },
  { id: 2, name: 'Wizards Guild', 
    type: 'Private', 
    image: '/images/kingdom.png', 
    description: 'Magic and strategy board game fans.', 
    members: 16 },
  { id: 3, name: 'Monopoly Club', 
    type: 'Public', 
    image: '/images/wingspan.jpg', 
    description: 'Weekly Monopoly sessions.', 
    members: 20 },
  { id: 4, name: 'Chess Masters', 
    type: 'Private', 
    image: '/images/civil.png', 
    description: 'Competitive chess community.', 
    members: 8 },
  { id: 5, name: 'Board Game Nerds', 
    type: 'Public', 
    image: '/images/omp.png', 
    description: 'All board games welcome.', 
    members: 30 },
  { id: 6, name: 'Strategy Kings',
    type: 'Public', 
    image: '/images/azul.jpg', 
    description: 'For lovers of strategy games.', 
    members: 12 },
]