export const events = [
  {
    id: 1,
    name: 'Catan Night',
    game: 'Catan',
    date: '2026-06-01',
    time: '18:00',
    location: 'Pretoria',
    visibility: 'Public',
    communityId: 1,
    organiser: 'Breezy',
    attendees: ['Breezy', 'Alex', 'You'],
    rsvped: false,
  },
  {
    id: 2,
    name: 'Wingspan Tournament',
    game: 'Wingspan',
    date: '2026-06-07',
    time: '14:00',
    location: 'Cape Town',
    visibility: 'Public',
    communityId: 5,
    organiser: 'Alex',
    attendees: ['Alex'],
    rsvped: false,
  },
  {
    id: 3,
    name: 'Private Chess Session',
    game: 'Chess',
    date: '2026-06-10',
    time: '10:00',
    location: 'Online',
    visibility: 'Private',
    communityId: 4,
    organiser: 'Joe',
    attendees: ['Joe', 'Breezy'],
    rsvped: false,
  },
  {
    id: 4,
    name: 'Monopoly Marathon',
    game: 'Monopoly',
    date: '2026-06-15',
    time: '12:00',
    location: 'Johannesburg',
    visibility: 'Public',
    communityId: 3,
    organiser: 'You',
    attendees: ['You', 'Alex'],
    rsvped: true,
  },
]