spring.application.name=backend
spring.data.mongodb.uri=${DB_URL}
spring.data.mongodb.database=boardwise
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

server.port=8080

jwt.secret=${JWT_SECRET}

# Cloudflare R2
r2.account-id=${R2_ACCOUNT_ID}
r2.access-key=${R2_ACCESS_KEY}
r2.secret-key=${R2_SECRET_KEY}
r2.bucket-name=${R2_BUCKET_NAME}

logging.level.org.springframework.boot.context.config=DEBUG
spring.profiles.active=dev