spring.application.name=backend
spring.mongodb.uri=${DEV_DB_URL}
spring.mongodb.database=boardwise
ai.gateway.url=${DEV_FAST_API_BASE}
ai.gateway.internal-secret=${INTERNAL_SECRET}
spring.data.mongodb.auto-index-creation=true
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

server.port=8080

jwt.secret=${JWT_SECRET}

# Cloudflare R2
r2.account-id=${R2_ACCOUNT_ID}
r2.access-key=${R2_ACCESS_KEY}
r2.secret-key=${R2_SECRET_KEY}
r2.bucket-rulebooks=${R2_BUCKET_RULEBOOKS}
r2.bucket-profiles=${R2_BUCKET_PROFILES}
r2.bucket-listings=${R2_BUCKET_LISTINGS}
r2.rulebooks.public-dev-url=${R2_RULEBOOKS_PUBLIC_DEV_URL}
r2.listings.endpoint=${R2_LISTINGS_ENDPOINT}
r2.rulebooks.public-prod-url=${R2_RULEBOOKS_PUBLIC_PROD_URL}
r2.listings.prod.endpoint=${R2_LISTINGS_PROD_ENDPOINT}
r2.dev-url=${R2_DEV_URL} 
r2.prod-url=${R2_PROD_URL}

# BGG STUFF
bgg.token={BGG_TOKEN}
bgg.url={BGG_URL}

# change or make new variable during production


# jackson stuff
spring.jackson.mapper.accept-case-insensitive-enums=true

logging.level.org.springframework.boot.context.config=DEBUG
spring.profiles.active=dev

spring.web.resources.add-mappings=false

#PLAYWRIGHT
scrape.cache.ttl.minutes=120
#1 hour
scrape.cache.refresh.interval.ms=3600000

google.maps.api-key=${GOOGLE_MAP_API_KEY}
