name: Deploy application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build and deploy application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm ci --ignore-scripts
          npm run build 

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: './IaC/requirements.txt'

      - name: Install Pulumi Requirements
        working-directory: ./IaC
        run: | # line 39 below
          pip install -r requirements.txt --only-binary=:all: 

      - name: Authenticate into AWS 
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run Pulumi Script
        uses: pulumi/actions@8e5e406f4007fca908480587cb9893c07090f58d
        with: 
          command: up
          stack-name: dev
          work-dir: ./IaC
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PROD_DB_URL: ${{ secrets.DB_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
          R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
          R2_BUCKET_RULEBOOKS: ${{ secrets.R2_BUCKET_RULEBOOKS }}
          R2_BUCKET_PROFILES: ${{ secrets.R2_BUCKET_PROFILES }}
          R2_BUCKET_LISTINGS: ${{ secrets.R2_BUCKET_LISTINGS }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          INTERNAL_SECRET: ${{ secrets.INTERNAL_SECRET }}
          CPU_CORES: ${{ secrets.CPU_CORES }}
          R2_LISTINGS_PROD_ENDPOINT: ${{ secrets.R2_LISTINGS_ENDPOINT}}
          R2_RULEBOOKS_PUBLIC_PROD_URL: ${{ secrets.R2_RULEBOOKS_PUBLIC_URL }}
          R2_PROD_URL: ${{ secrets.R2_PROD_URL }}
          BGG_TOKEN: ${{ secrets.BGG_TOKEN }}
          BGG_URL: ${{ secrets.BGG_URL }}
          GOOGLE_MAP_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
    
      - name: Get CloudFront Distro ID
        id: get_distro
        working-directory: ./IaC
        run: |
          DISTRO_ID=$(pulumi stack output cloudfront_distro_id -s dev)
          echo "DISTRO_ID=$DISTRO_ID" >> $GITHUB_ENV
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DISTRO_ID }} \
            --paths "/*"
           